### ISSUE TITLE
Ubuntu 22.10 version ?

### ISSUE THREAD

**Issue by Rayzeq** [lubomir-brindza/nautilus-typeahead#16]
Since the 22.10 was released some time ago, I was wondering if you plan to post the patched nautilus for this version, unless the patch doesn't work for this new version of nautilus?

**Comment by lubomir-brindza** [comment]
I've been lagging behind a bit since my main workstation was kept back to 22.04 until today, so apologies for the late reply.

Bad news there, I'm afraid.

Unfortunately, the upstream patch will no longer apply to nautilus 43.0, since it's been through some major rework - ex.: `src/nautilus-list-view.c` went from ~4k lines in 42.2 to ~1k in 43.0 and, to put it simply, the bits of code the patch is trying to modify are no longer there.

The resulting amount of work to make the patch work again (or make one from scratch) is non-trivial, so it may take some time for someone to create a working patch again. My experience is not up to the task, so this is where we are stuck for now.
 
Link to the patch author's remarks here: https://aur.archlinux.org/packages/nautilus-typeahead#comment-887750

**Comment by Rayzeq** [comment]
Yeah, that's what I thought, it's a real shame that this feature is not builtin because it's really good.

**Comment by bryango** [comment]
I have checked that the patch https://gitlab.gnome.org/GNOME/nautilus/-/merge_requests/1030 by `@xclaesse` works for me. Do note that some nautilus extensions (python or otherwise) may no longer work in v43. I've mirrored the patch on gitlab, see:

- https://github.com/bryango/nautilus-typeahead/compare/master..type-ahead
- https://github.com/bryango/nautilus-typeahead/compare/master..type-ahead.patch

I've also made a PKGBUILD for arch. See the related comment on the AUR: https://aur.archlinux.org/pkgbase/nautilus-typeahead#comment-900609.

**Comment by lubomir-brindza** [comment]
Cheers for that; I'll try to make time and have a look at it.

**Comment by bryango** [comment]
Also, as pointed out by the AUR package maintainer [`@albertvaka`](https://aur.archlinux.org/pkgbase/nautilus-typeahead#comment-901017) it would be great if you can ask users to upvote the upstream issue, requesting type-ahead to be added back to Nautilus: https://gitlab.gnome.org/Teams/Design/whiteboards/-/issues/142.

The patch is working but GNOME is just refusing to change... :face_exhaling: Our voice needs to be heard.

**Comment by lubomir-brindza** [comment]
So, patched 43.0 is out and available in the PPA.

There are some changes that may take a while to get accustomed to; namely you first need to opt-out of the default search behavior in settings, and the little text box that'd pop-out in the lower right corner of the window is gone, but overall I'm happy with the behavior. Implementation seems a lot cleaner than it was before, too.

Seems like 43.2 is about to be released; hopefully this'll still work :D

**Comment by sryze** [comment]
@lubomir-brindza is it possible to create an extension instead of patching Nautilus code? Or the extension API doesn't provide the necessary things?

**Comment by lubomir-brindza** [comment]
I'm not sure! As mentioned in the readme, I didn't actually write the patch for nautilus - I just maintain the PPA package so that you don't have to compile it from source yourself. I don't have the know-how and/or knowledge of the nautilus internals to respond to your question.

I'm actually somewhat hopeful this functionality will be reintroduced by default _eventually_, as the [whiteboard discussion](https://gitlab.gnome.org/Teams/Design/whiteboards/-/issues/142) has turned out better than most similar threads (i.e. it hasn't been closed yet). The current patch (that was proposed as a prototype) still needs work, and it's currently not a priority for the nautilus design team to work on it - but that can change. Be sure to thumbs-up the issue so that they can better gauge the users' interest in this feature.
